config/routes.rb
Rails.application.routes.draw do
  root "games#index"

  devise_for :users

  resources :games do
    resources :races
  end

  resources :races do
    resources :units
  end
  
  
  #post 'games/choose_game', 'games#choose'
  # resources :races do 
  #   resources :units
  # end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :races, dependent: :destroy
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :units, dependent: :destroy
  belongs_to :game
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :race
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def main
    render 'layouts/main'
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
    render "form"
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
    else
      render "form"
    end
  end

  def edit
    render "form"
  end

  def update
    if @game.update(game_params)
      redirect_to games_path
    else
      render "form"
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end
 
  private
  def game_params
    params.require(:game).permit(:name)
  end

  def set_game
    @game = Game.find(params[:id])
  end

end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :get_race, only: [:update, :edit, :show, :destroy]
  before_action :get_game
  before_action :get_races

  def index
    @races = @game.races
  end

  def new
    @race = @game.races.new
    render "form"
  end

  def create
    @race = @game.races.new(race_params)
    if @race.save
      redirect_to game_races_path(@game)
    else
      render "form"
    end
  end

  def edit
    render "form"
  end

  def update
    if @race.update(race_params)
      redirect_to game_races_path
    else
      render "form"
    end
  end

  def show
  end

  def destroy
    @race.destroy
    redirect_to game_races_path
  end

  private
    def race_params
      params.require(:race).permit(:name, :game_id)
    end

     def get_race
       @race = Race.find(params[:id])
     end

    def get_game
      @game = Game.find(params[:game_id])
    end

    def get_races
      @races = @game.races
    end
    
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :get_unit, only: [:update, :edit, :show, :destroy]
  before_action :get_race

  def index
    @units = @races.units
  end

  def new
    @unit = @race.units.new
    render "form"
  end

  def create
    @unit = @race.units.new(unit_params)
    if @unit.save
      redirect_to race_units_path(@race)
    else
      render "form"
    end
  end

  def edit
    render "form"
  end

  def update
    if @unit.update(unit_params)
      redirect_to race_units_path
    else
      render "form"
    end
  end

  def show
  end

  def destroy
    @unit.destroy
    redirect_to race_units_path
  end

  private
    def unit_params
      params.require(:unit).permit(:name, :speed, :melee, :range, :defense, :attack, :nerve, :point, :race_id)
    end

     def get_unit
       @unit = Unit.find(params[:id])
     end

    def get_race
      @race = Race.find(params[:race_id])
    end
    
end

t.string "name"
    t.string "type"
    t.string "speed"
    t.string "melee"
    t.string "range"
    t.string "defense"
    t.string "attack"
    t.string "nerve"
    t.string "point"
    t.bigint "race_id"

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/races_helper.rb
module RacesHelper
  def self.get_races(game)
    @races = game.races
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/games/form.html.erb
<h1><%= @game.name ? "Edit " : "New " %>Game</h1>
<div class="form_input"><%= form_with(model: @game, local: true) do |f| %><?div>
<div class="form_input_label"><%= f.label :name %></div>
<div class="form_input"><%= f.text_field :name %></div>
<div class="form_input"><%= f.submit %></div>
<% end %>
</hr>

app/views/games/index.html.erb
<div id="full-page-container">
<div id="inner-page-container">

  <div id="nav-bar-container">
  <%= render '/layouts/navbar' %>
  </div>

  <div> . </div> 

app/views/games/show.html.erb
<div id="full-page-container">
<div id="inner-page-container">

  <div id="nav-bar-container">
  <%= render '/layouts/navbar' %>
  </div>
  <div id="two-column-container" class="warhammer-map">
      <div id="main-column1">
      <%= render '/layouts/all_units' %>
      </div>
      <div id="main-column2">
      <%= render '/layouts/user_army_list' %>
      </div>
  </div>

</div>
</div>

app/views/layouts/_all_units.html.erb
<%= render '/races/index' %>

app/views/layouts/_navbar.html.erb
<div>
<div class="navbar" style="margin: 0; padding: 0;">
<% @games = Game.all %>
<% @games.each do |game| %>
<a><%= link_to game.name, game_path(game), method: :get, class: "nav-item" %></a>
<% end %>
<a><%= link_to "+", new_game_path, class: 'nav-item' %></a>

<div class="nav-item-empty">
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>
</div>


<div class="nav-item" id="user-sign-in" >
  <% if user_signed_in? %>
    <%= link_to current_user.email, edit_user_registration_path %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>

</div>
</div>

app/views/layouts/_user_army_list.html.erb
<div>User Army List</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Armycreate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/races/_index.html.erb
<h1>Races</h1>
<div class="warhammer-map">

  <% RacesHelper.get_races(@game).each do |race| %>
    <div>
    <%= link_to race.name, game_race_path(@game, race), class: "text_link" %>
    </div>
  <% end %>
</div>

app/views/races/form.html.erb
<h1><%= @race.name ? "Edit " : "New " %>Race</h1>
<div class="form_input"><%= form_with(model: [@game, @race], local: true) do |f| %><?div>
<div class="form_input_label"><%= f.label :name %></div>
<div class="form_input"><%= f.text_field :name %></div>
<div class="form_input"><%= f.submit %></div>
<% end %>
</hr>

app/views/races/show.html.erb
<h2><%= @race.name %> 

<div>
  <% @races.units.each do |unit| %>
    <div>
    <%= unit.name, (@race, unit), %>
    </div>
  <% end %>
</div>

<%= link_to "| back", game_races_path %> </h2>

app/views/units/form.html.erb
<h1><%= @unit.name ? "Edit " : "New " %>Unit</h1>
<div class="form_input"><%= form_with(model: [@race, @unit], local: true) do |f| %><?div>
<div class="form_input_label"><%= f.label :name %></div>
<div class="form_input"><%= f.text_field :name %></div>

<div class="form_input_label"><%= f.label :type %></div>
<div class="form_input"><%= f.select :type, ("Hero", "Core", "Special") %></div>

<div class="form_input_label"><%= f.label :speed %></div>
<div class="form_input"><%= f.text_field :speed %></div>

<div class="form_input_label"><%= f.label :melee %></div>
<div class="form_input"><%= f.text_field :melee %></div>

<div class="form_input_label"><%= f.label :range %></div>
<div class="form_input"><%= f.text_field :range %></div>

<div class="form_input_label"><%= f.label :defense %></div>
<div class="form_input"><%= f.text_field :defense %></div>

<div class="form_input_label"><%= f.label :attack %></div>
<div class="form_input"><%= f.text_field :attack %></div>

<div class="form_input_label"><%= f.label :nerve %></div>
<div class="form_input"><%= f.text_field :nerve %></div>

<div class="form_input_label"><%= f.label :point %></div>
<div class="form_input"><%= f.text_field :point %></div>

<div class="form_input_label"><%= f.label :attack %></div>
<div class="form_input"><%= f.text_field :attack %></div>


<div class="form_input"><%= f.submit %></div>
<% end %>
</hr>

app/views/units/index.html.erb
<h1>Units#index</h1>
<p>Find me in app/views/units/index.html.erb</p>

app/views/units/show.html.erb
<h1>Units#show</h1>
<p>Find me in app/views/units/show.html.erb</p>